name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r download/release.zip "index.tbx" "calculate_fsi.py" "calculate_gsi.py" "import_and_footprint.py" "objsplit.py"
    - name: Release to Github
      run: echo "Release"
